
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Sun May 31 12:19:01 ART 2020
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "insertarDetalleAsistencia", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertarDetalleAsistencia", namespace = "http://ws.das.ubp.edu.ar/")

public class InsertarDetalleAsistencia {

    @XmlElement(name = "detalleAsistencia")
    private ar.edu.ubp.das.bean.DetalleAsistenciaBean detalleAsistencia;

    public ar.edu.ubp.das.bean.DetalleAsistenciaBean getDetalleAsistencia() {
        return this.detalleAsistencia;
    }

    public void setDetalleAsistencia(ar.edu.ubp.das.bean.DetalleAsistenciaBean newDetalleAsistencia)  {
        this.detalleAsistencia = newDetalleAsistencia;
    }

}

