
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Sun May 31 12:19:01 ART 2020
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "insertarChatAsistenciaResponse", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertarChatAsistenciaResponse", namespace = "http://ws.das.ubp.edu.ar/")

public class InsertarChatAsistenciaResponse {

    @XmlElement(name = "return")
    private javax.ws.rs.core.Response _return;

    public javax.ws.rs.core.Response getReturn() {
        return this._return;
    }

    public void setReturn(javax.ws.rs.core.Response new_return)  {
        this._return = new_return;
    }

}

